import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import Header from "@/components/header";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const gambarino = localFont({
  src: '../fonts/Gambarino-Regular.otf',
  weight: '400',
  variable: "--font-gambarino"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${raleway.className}`}
      >
        <Header/>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
